// Generated by the AI Software Factory (internal/testharness) — do not edit: it
// is rewritten on every run. Put tests in *.spec.ts files next to it and use
// relative URLs (page.goto('/')) — baseURL already points at the gateway.
import { defineConfig } from '@playwright/test';

export default defineConfig({
  testDir: '.',
  testIgnore: ['**/node_modules/**', 'screenshots/**'],
  workers: 1,
  retries: 0,
  forbidOnly: true,
  timeout: 30_000,
  reporter: [['./asf-reporter.cjs']],
  outputDir: '/output/test-results',
  use: {
    baseURL: process.env.BASE_URL ?? 'http://gateway',
  },
});
