#!/bin/sh
# Generated by the AI Software Factory (internal/testharness) — do not edit: it
# is rewritten on every run. Runs the API suite, then the Playwright suite when
# this image has one, and exits non-zero if either failed. Both print to stdout
# so every PASS/FAIL [api] and [e2e] line lands in the one tester log.
rc=0
echo "== component suite (api)"
/usr/local/bin/component-test || rc=1
if [ -f /e2e/playwright.config.ts ]; then
  echo "== e2e suite (playwright)"
  mkdir -p /output/screenshots
  (cd /e2e && ./node_modules/.bin/playwright test) || rc=1
fi
exit "$rc"
